#!/bin/sh
# Copyright (C) 2018 Apertus Solutions, LLC
# Licensed on MIT

integrity_enabled() {
    return 0
}

integrity_run() {
    if [ "${openxt_measured}" = "true" ]; then
        bootparam_init="/sbin/init.root-ro"
    fi

    bootparam_init="/sbin/integrity-load.sh ${bootparam_init:-/sbin/init} ${bootparam_runlevel}"
}
